Support the bug task status filter.

diff --git a/in b/in
--- a/in
+++ b/in
@@ -61,6 +61,23 @@ else
     id=()
 fi
 
+if [ "$(jq -r '.source | has("status")' < /tmp/input.json)" = 'true' ]; then
+    case "$(jq -r '.source.status | type' < /tmp/input.json)" in
+        ('string')
+            status=("$(jq -r .source.status < /tmp/input.json)")
+            ;;
+        ('array')
+            mapfile -t status < <(jq -r '.source.status | .[]' < /tmp/input.json)
+            ;;
+        (*)
+            echo "Invalid input for .source.status"
+            exit 1
+            ;;
+    esac
+else
+    status=()
+fi
+
 if [ "$(jq -r '.source | has("project")' < /tmp/input.json)" = 'true' ]; then
     project="$(jq -r .source.project < /tmp/input.json)"
 else
@@ -106,20 +123,28 @@ esac
 
 declare -A etag=()
 declare -A title=()
-declare -a tags=()
+declare -a args=()
 
 for name in "${tag[@]}"; do
-    tags+=("tags==$name")
+    args+=("tags==$name")
+done
+
+for name in "${status[@]}"; do
+    case "$name" in
+        ("New"|"Incomplete"|"Opinion"|"Invalid"|"Won't Fix"|"Expired"|"Confirmed"|"Triaged"|"In Progress"|"Fix Committed"|"Fix Released"|"Unknown")
+            args+=("status==$name")
+            ;;
+        (*)
+            echo "$name is not a valid status."
+            exit 1
+            ;;
+    esac
 done
 
 if [ -n "$project" ]; then
     tmp=$(mktemp -u /tmp/json-XXXXXX)
 
-    if [ -z "${tag[*]}" ]; then
-        oauth_consumer_key="$oauth_consumer_key" launchpad-api get "$project" ws.op==searchTasks > "$tmp"
-    else
-        oauth_consumer_key="$oauth_consumer_key" launchpad-api get "$project" ws.op==searchTasks "${tags[@]}" tags_combinator=="$combinator" > "$tmp"
-    fi
+    oauth_consumer_key="$oauth_consumer_key" launchpad-api get "$project" ws.op==searchTasks "${args[@]}" tags_combinator=="$combinator" > "$tmp"
 
     while read -r bug_link; do
         id+=("$(basename "$bug_link")")
